MERGE INTO VACANCY v
USING (
    SELECT 1 as VACANCY_ID, 3 as EMPLOYER_ID, 'Apple' as COMPANY_NAME, 'Java Developer' as POSITION_TITLE, 'Java, Spring' as REQUIREMENTS,
        null as DESCRIPTION, 1 as ACTIVE, TO_DATE('2023-08-13 10:12:09', 'YYYY-MM-DD HH:mm:ss') as CREATED_ON,
        TO_DATE('2023-08-15 10:12:09', 'YYYY-MM-DD HH:mm:ss') as UPDATED_ON FROM dual
        UNION ALL
    SELECT 2 as VACANCY_ID, 3 as EMPLOYER_ID, 'Apple' as COMPANY_NAME, 'JS Developer' as POSITION_TITLE, 'JS, HTML, CSS' as REQUIREMENTS,
        null as DESCRIPTION, 0 as ACTIVE, TO_DATE('2023-08-23 10:12:09', 'YYYY-MM-DD HH:mm:ss') as CREATED_ON,
        TO_DATE('2023-08-15 10:12:09', 'YYYY-MM-DD HH:mm:ss') as UPDATED_ON FROM dual
        UNION ALL
    SELECT 3 as VACANCY_ID, 2 as EMPLOYER_ID, 'Google' as COMPANY_NAME, 'Java Developer' as POSITION_TITLE, 'Java, Spring, SQL' as REQUIREMENTS,
        null as DESCRIPTION, 1 as ACTIVE, TO_DATE('2023-06-10 10:12:09', 'YYYY-MM-DD HH:mm:ss') as CREATED_ON,
        TO_DATE('2023-08-15 10:12:09 10:12:09', 'YYYY-MM-DD HH:mm:ss') as UPDATED_ON FROM dual
        UNION ALL
    SELECT 4 as VACANCY_ID, 3 as EMPLOYER_ID, 'Apple' as COMPANY_NAME, 'React Developer' as POSITION_TITLE, 'React.js, JS' as REQUIREMENTS,
        null as DESCRIPTION, 1 as ACTIVE, TO_DATE('2023-07-09 10:12:09', 'YYYY-MM-DD HH:mm:ss') as CREATED_ON,
        TO_DATE('2023-08-15 10:12:09', 'YYYY-MM-DD HH:mm:ss') as UPDATED_ON FROM dual
        UNION ALL
    SELECT 5 as VACANCY_ID, 3 as EMPLOYER_ID, 'Apple' as COMPANY_NAME, 'Devops' as POSITION_TITLE, 'Docker' as REQUIREMENTS,
        null as DESCRIPTION, 1 as ACTIVE, TO_DATE('2023-09-24 10:12:09', 'YYYY-MM-DD HH:mm:ss') as CREATED_ON,
        TO_DATE('2023-08-15 10:12:09', 'YYYY-MM-DD HH:mm:ss') as UPDATED_ON FROM dual
        UNION ALL
    SELECT 6 as VACANCY_ID, 2 as EMPLOYER_ID, 'Google' as COMPANY_NAME, 'Devops' as POSITION_TITLE, 'Docker' as REQUIREMENTS,
        null as DESCRIPTION, 1 as ACTIVE, TO_DATE('2023-10-18 10:12:09', 'YYYY-MM-DD HH:mm:ss') as CREATED_ON,
        TO_DATE('2023-08-15 10:12:09', 'YYYY-MM-DD HH:mm:ss') as UPDATED_ON FROM dual
) res
ON (v.VACANCY_ID = res.VACANCY_ID)
WHEN NOT MATCHED THEN
    INSERT (VACANCY_ID, EMPLOYER_ID, COMPANY_NAME, POSITION_TITLE, REQUIREMENTS, DESCRIPTION, ACTIVE, CREATED_ON, UPDATED_ON)
    VALUES (res.VACANCY_ID, res.EMPLOYER_ID, res.COMPANY_NAME, res.POSITION_TITLE, res.REQUIREMENTS, res.DESCRIPTION, res.ACTIVE,
        res.CREATED_ON, res.UPDATED_ON);